# Generated by Django 4.2.4 on 2023-11-21 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_c', models.AutoField(db_column='rut_c', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_e', models.CharField(db_column='rut_e', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('ids', models.AutoField(db_column='idS', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('ida', models.AutoField(db_column='idA', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('reserva', models.BooleanField()),
                ('cliente_rut_c', models.ForeignKey(db_column='Cliente_rut_c', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('empleado_rut_e', models.ForeignKey(db_column='Empleado_rut_e', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empleado')),
                ('servicio_ids', models.ForeignKey(db_column='Servicio_idS', on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicio')),
            ],
            options={
                'db_table': 'Atencion',
                'managed': True,
            },
        ),
    ]
